before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  - pip3 install pipenv
  - pipenv install --dev --ignore-pipfile

test_package:
  tags:
    - python-numpy
  script:
    - make test
    - make lint

make-doc:
  only:
    - master
  tags:
    - python-numpy
  script:
    - ssh-add <(echo "$SSH_PRIVATE_KEY_HAL")
    - make doc
    - scp -r ./documentation/build/html $DOC_LOCATION
