before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  - pip3 install --upgrade -r requirements.txt -r requirements-dev.txt

test_package:
  tags:
    - python-numpy
  script:
    - python3 setup.py test
    - make lint

make-doc:
  tags:
    - python-numpy
  script:
    - ssh-add <(echo "$SSH_PRIVATE_KEY_HAL")
    - python setup.py install
    - make doc
    - scp -r ./documentation/build/html $DOC_LOCATION
