source: dev
target: master
version: qcip_tools.__version__
remotes:
  - origin
  - unamur
# tag:
tag_release:
  tag: 'release-v{version}'
# update README:
update_readme:
  commit_message: 'update README for version {version}'
  format: md
  file: README.md
  stable_line_indicator: '<!-- STABLE: -->'
  previous_line_indicator: '<!-- PREVIOUS: -->'
  text_before: 'Current release:'
  url: 'https://gitlab.unamur.be/chimie/lct/qcip_tools'